server:
  port: 5010

spring:
  application:
    name: service-consumer

# 配置 eureka server 注册中心
eureka:
  instance:
    prefer-ip-address: true #是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
    register-with-eureka: true #是否将自己注册到注册中心，默认为true
    registry-fetch-interval-seconds: 10 # 表示Eureka Client 间隔多久去服务器拉取注册信息，默认为30秒
    serviceUrl: #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8671/eureka/,http://root:123456@localhost:8672/eureka/

# feign 开启 Hytrix 支持
feign:
  hystrix:
    enabled: true


# 度量指标监控与健康监测
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
