server:
  port: 9000

spring:
  application:
    name: zuul-server

# 路由规则 ,简化路由注释 zuul 下面所有
zuul:
  # 路由前缀
#  prefix: /api
  routes:
    serviceSentinelProvider:  #路由 id ，自定义
      path: /serviceSentinelProvider/** # 配置请求 url 的映射路径
      # 1、url 路由模式
      #url: http://localhost:7070/ #映射路径对应的微服务地址
      # 2、服务名称路由
      serviceId: serviceSentinelProvider #根据 serviceId 自动从注册中心获取


  # 禁用 zuul 默认的异常处理 filter
  SendErrorFilter:
    error:
      disable: true

# 配置 eureka server 注册中心
eureka:
  instance:
    prefer-ip-address: true #是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
    serviceUrl: #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8671/eureka/,http://root:123456@localhost:8672/eureka/

# 度量指标监控与健康监测
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream