server:
  port: 5010

  tomcat:
    max-threas: 3 #降低最大线程数方便模拟高并发

  #gzip 压缩 全局方式
  compression:
    enabled: true #是否开启压缩
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


spring:
  application:
    name: service-consumer

  # 开启 Transport 模块与 Sentinel 控制台进行通信
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

      #动态规则配置
      datasource:
        ds1:
          file:
            file: classpath:flowRule.json
            data-type: json
            rule-type: flow

# 配置 eureka server 注册中心
eureka:
  instance:
    prefer-ip-address: true #是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
    register-with-eureka: true #是否将自己注册到注册中心，默认为true
    registry-fetch-interval-seconds: 10 # 表示Eureka Client 间隔多久去服务器拉取注册信息，默认为30秒
    serviceUrl: #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8671/eureka/,http://root:123456@localhost:8672/eureka/
