server:
  port: 9090

spring:
  application:
    name: service-consumer

  cloud:
    loadbalancer:
      ribbon:
        enabled: true

# 配置 eureka server 注册中心
eureka:
  client:
    register-with-eureka: false #是否将自己注册到注册中心，默认为true
    registry-fetch-interval-seconds: 10 # 表示Eureka Client 间隔多久去服务器拉取注册信息，默认为30秒
    serviceUrl: #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8671/eureka/,http://root:123456@localhost:8672/eureka/

# 负载均衡策略 - 局部方式
# serviceProvider 为调用的服务的名称
serviceProvider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略

